### PR TITLE
installation instructions

### PR DESCRIPTION
**Pull request by bluemix**
appending how to install the package as a dart package

### CODE REVIEW

**Review by efortuna — CHANGES_REQUESTED** [review]
Please leave the description up at the top ("A very basic cover flow implementation to swipe between widgets in Flutter.") and put the installation section below that. Also please don't specify the specific version number (^0.0.7) because it will get out of date as it gets updated. Just add LATEST_VERSION_NUMBER or something to in that line.

**Review by bluemix — COMMENTED** [review]
moving installation section below project description

**Comment by bluemix** [comment]
i hope the new pull request is aligned with your request :)

**Review by efortuna — APPROVED** [review]
looks good, thank you!

**Pull request merged**
